# Generated by Django 2.0.3 on 2018-03-26 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_int', models.PositiveSmallIntegerField(default=1)),
                ('octave', models.PositiveSmallIntegerField(default=3)),
                ('velocity', models.PositiveSmallIntegerField(default=5)),
                ('envelope_amount', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='untitled', max_length=35)),
                ('length', models.PositiveSmallIntegerField(default=8)),
                ('scale_type', models.CharField(default='major', max_length=50)),
                ('key', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='untitled', max_length=35)),
                ('bpm', models.PositiveSmallIntegerField(default=120)),
            ],
        ),
        migrations.CreateModel(
            name='SynthPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Preset', max_length=35)),
                ('osc_waveform', models.CharField(max_length=35)),
                ('amp_gain', models.FloatField()),
                ('amp_attack', models.FloatField()),
                ('amp_decay', models.FloatField()),
                ('amp_sutain', models.FloatField()),
                ('amp_release', models.FloatField()),
                ('distortion_amount', models.FloatField()),
                ('distortion_wet', models.FloatField()),
                ('filter_type', models.CharField(default='lowpass', max_length=35)),
                ('filter_frequency', models.FloatField()),
                ('filter_resonance', models.FloatField()),
                ('filter_attack', models.FloatField()),
                ('filter_decay', models.FloatField()),
                ('filter_sustain', models.FloatField()),
                ('filter_release', models.FloatField()),
                ('lfo_waveform', models.CharField(default='sine', max_length=50)),
                ('lfo_frequency', models.FloatField()),
                ('lfo_depth', models.FloatField()),
                ('lfo_sync_st', models.BooleanField()),
                ('lfo_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('chorus_depth', models.FloatField()),
                ('chorus_frequency', models.FloatField()),
                ('chorus_delay', models.FloatField()),
                ('chorus_feedback', models.FloatField()),
                ('chorus_wet', models.FloatField()),
                ('fbdk_delay_time', models.FloatField()),
                ('fdbk_delay_fdbk', models.FloatField()),
                ('fdbk_delay_wet', models.FloatField()),
                ('reverb_dampening', models.FloatField()),
                ('reverb_size', models.FloatField()),
                ('reverb_wet', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='sequence',
            name='preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiddleapp.SynthPreset'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiddleapp.Song'),
        ),
        migrations.AddField(
            model_name='note',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiddleapp.Sequence'),
        ),
    ]
