# Generated by Django 2.0.3 on 2018-04-05 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiddleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_int', models.CharField(max_length=2)),
                ('octave', models.PositiveSmallIntegerField(default=3)),
                ('velocity', models.SmallIntegerField(default=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='key',
        ),
        migrations.AddField(
            model_name='sequence',
            name='root_note',
            field=models.CharField(default='C', max_length=2),
        ),
        migrations.AddField(
            model_name='song',
            name='preset',
            field=models.ManyToManyField(blank=True, null=True, related_name='song', to='fiddleapp.SynthPreset'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiddleapp.SynthPreset'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='scale_type',
            field=models.CharField(default='Chromatic', max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(default='untitled', max_length=50),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.AddField(
            model_name='beat',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiddleapp.Sequence'),
        ),
    ]
