# Generated by Django 2.0.4 on 2018-04-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiddleapp', '0002_auto_20180405_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='preset',
            field=models.ManyToManyField(related_name='song', to='fiddleapp.SynthPreset'),
        ),
    ]
