# Generated by Django 2.0.4 on 2018-04-12 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiddleapp', '0005_auto_20180412_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='synthpreset',
            old_name='amp_attack',
            new_name='amplifier_attack',
        ),
        migrations.RenameField(
            model_name='synthpreset',
            old_name='amp_decay',
            new_name='amplifier_decay',
        ),
        migrations.RenameField(
            model_name='synthpreset',
            old_name='amp_release',
            new_name='amplifier_release',
        ),
        migrations.RenameField(
            model_name='synthpreset',
            old_name='amp_sutain',
            new_name='amplifier_sutain',
        ),
        migrations.RenameField(
            model_name='synthpreset',
            old_name='filter_env_attack',
            new_name='filter_envelope_attack',
        ),
        migrations.RenameField(
            model_name='synthpreset',
            old_name='filter_env_base_frequency',
            new_name='filter_envelope_base_frequency',
        ),
        migrations.RenameField(
            model_name='synthpreset',
            old_name='filter_env_decay',
            new_name='filter_envelope_decay',
        ),
        migrations.RenameField(
            model_name='synthpreset',
            old_name='filter_env_exponent',
            new_name='filter_envelope_exponent',
        ),
        migrations.RenameField(
            model_name='synthpreset',
            old_name='filter_env_octaves',
            new_name='filter_envelope_octaves',
        ),
        migrations.RenameField(
            model_name='synthpreset',
            old_name='filter_env_release',
            new_name='filter_envelope_release',
        ),
        migrations.RenameField(
            model_name='synthpreset',
            old_name='filter_env_sustain',
            new_name='filter_envelope_sustain',
        ),
        migrations.RemoveField(
            model_name='synthpreset',
            name='filter_env_attack_curve',
        ),
        migrations.RemoveField(
            model_name='synthpreset',
            name='filter_env_release_curve',
        ),
        migrations.RemoveField(
            model_name='synthpreset',
            name='name',
        ),
    ]
