# Generated by Django 2.0.4 on 2018-04-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiddleapp', '0006_auto_20180412_0410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='synthpreset',
            old_name='amplifier_sutain',
            new_name='amplifier_sustain',
        ),
        migrations.AddField(
            model_name='synthpreset',
            name='filter_frequency',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
